### ISSUE TITLE
BotBuilder-CognitiveServices for v3 or v4 Bot.?

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder-CognitiveServices#125]
I have few questions on [](https:/https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/Node/samples/QnAMaker/github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/Node/samples/QnAMaker)

Is this module BotBuilder-CognitiveServices for v3 bot or v4?
Ways to access QnA are mentioned in QnAMaker above. Is this the only way to access QnA in V3 bot ?

**Comment by stevengum** [comment]
This module is one of the ways to access QnA Maker in a v3 bot. You can otherwise just construct a regular [HTTP request to call QnA Maker like the SDK does](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/Node/src/QnAMakerRecognizer.ts#L149) using the [request package](https://www.npmjs.com/package/request).

To access QnA Maker in the v4 Bot Builder SDK, you can use the [QnAMaker class](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-ai/src/qnaMaker.ts#L132), which can be found in the [botbuilder-js](https://github.com/Microsoft/botbuilder-js) repo.

If you're asking about which version of QnA Maker to is supported, preview or GA, then in the v3 and v4 BotBuilder SDKs, both are supported.

**Comment by rjgmail88** [comment]
@stevengum , Sorry for not being clear. But, I have 2 questions. 

1. Is this module BotBuilder-CognitiveServices for v3 bot or v4? - Which I think answer is YES, I can use BotBuilder-CognitiveServices for my v3 bot. 

2.  Is this the only way to access QnA in V3 bot ? - let' say I dont want to use BotBuilder-CognitiveServices package (if its not licensed or GA?) the HTTP request is the only way to there is something else that I dont know about.

**Comment by rjgmail88** [comment]
@stevengum , just bumping this if you missed my comment.

**Comment by stevengum** [comment]
1. Yes
2. This isn't the only way to access QnA Maker, the package just provides a series of APIs that perform HTTP calls on your behalf. You can roll your own custom solution to call QnA Maker and forgo this package. QnA Maker and LUIS are only accessible via HTTP calls at this time.
