### ISSUE TITLE
[QnA maker]QnAMaker confidence scores strange change

### ISSUE THREAD

**Issue by YutongTie-MSFT** [Microsoft/BotBuilder-CognitiveServices#148]
Hi team,

It seems the scores has strange changes according to the document https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/concepts/confidence-score. I have use the same QnA pair and also I use the same question, but the scores have big differences between the document and the real result.

I have one customer reported in MSDN forum, please check it as well.
https://social.msdn.microsoft.com/Forums/windows/en-US/33bcaf0c-ece3-4c89-9b93-b2abc250f993/qnamaker-confidence-scores-dropped-since-september-2018?forum=AzureCognitiveService

Is this a bug or a algorithm updated? 

Thanks a lot!

**Comment by stevkan** [comment]
Hi @YutongTie-MSFT, Are you still experiencing a difference in scores? One consideration to remember is QnAMaker is non-deterministic. This means that scores can vary.

**Comment by YutongTie-MSFT** [comment]
@stevkan Yes. I understand what you mean, but I don't think the score should be so different.... Like from around 98 to 56

**Comment by YutongTie-MSFT** [comment]
@stevkan Any update?

**Comment by EdwinOtten** [comment]
Hi, I'm the customer that reported this issue.

I understand that we can't expect to get exactly the same score due to the non-deterministic algorithm. I do think the algorithm should return similar scores.. So if the documentation says _90 - 100_, I don't think we should accept a score of 43 for exactly the same query.

To eliminate as many factors possible I created a brand new KB and trained it with the exact same information as the example in the documentation. I then got these scores:

Typical Score | My Score | Query
--|--|--
90 - 100 | 43.09❗ | "My changes aren't updated in Knowledge base after publish"
70+ | 49.34❗ | "I published my KB but it's not updated"
50 - 70 | 54.49 | "Should I save my updates before I publish my KB?"
30 - 50 | None❗ | "What does the save and train do?"
< 30 | 16.75 | "Where can I add synonyms to my KB"
0 | 8.57 | "How much does the service cost"

**Comment by YutongTie-MSFT** [comment]
@EdwinOtten Thanks for your details. I am still following this issue.

**Comment by stevkan** [comment]
@YutongTie-MSFT, I've reached out to the QnA team and am awaiting a response on this particular issue. I will keep you updated as I know more.

**Comment by stevkan** [comment]
@YutongTie-MSFT, can I ge a copy of the kB that is producing the unusual scores as well its kb id? This will allow us to dig deeper into any anomalies that might be affecting the scores.

**Comment by EdwinOtten** [comment]
This is the export (.tsv) of the KB I'm testing against:
```
Question	Answer	Source	Metadata
The updates that I made to my knowledge base are not reflected on publish. Why not?	Every edit operation, whether in a table update, test, or settings, needs to be saved before it can be published. Be sure to click the Save and train button after every edit operation.	https://docs.microsoft.com/azure/cognitive-services/qnamaker/faqs	
My changes are not updated in the KB after publish  	Every edit operation, whether in a table update, test, or settings, needs to be saved before it can be published. Be sure to click the Save and train button after every edit operation.	https://docs.microsoft.com/azure/cognitive-services/qnamaker/faqs
```

I assume you can't access our KB but it's ID is `c9127347-94a5-4614-92a3-af295b7d7130`.

**Comment by stevkan** [comment]
@EdwinOtten, thank you for the file and the id.

**Comment by stevkan** [comment]
@YutongTie-MSFT @EdwinOtten, the QnA team checked the kb id and stated that host **chatbotqnamakertest** is using ranker v0. This ranker is not the most recent version. They will migrate this host to the most current after which you can test confidence scores for better parity vs. the docs.

They would like to know if there are other apps you would like to have migrated. If you could please list any other kb id's, that would be great. I will forward those to the QnA team. It will take a day+ to migrate once I submit the kb ids.

Lastly, I asked what the process should be for the future should any other QnA apps be created a day/week/month from now.

**Comment by EdwinOtten** [comment]
@stevkan Yes we have three other KB's that I would like to migrate:
```
417ae19b-ffaa-4a3f-9ee0-84efde0c76c4
90ff37ce-1135-4cd6-9f80-3ff54c008b06
17377303-1422-432e-b9c7-89f261255519 *
```
\* this one may already be on the most recent ranker, because it was created 5 days ago..

My team is somewhat surprised that this is not a fully automated process. For the sake of other developers that might be reading along, is there a way to migrate without your help? (e.g. creating a new KB from scratch and importing the old one)

**Comment by YutongTie-MSFT** [comment]
@stevkan  Thanks for your help. If my understanding is not wrong, all the KBs created before we filed the bug all depended on the ranker v0, which is not exact? Just want to make sure so that I can help customers with the same problem.

**Comment by stevkan** [comment]
@EdwinOtten, I have already submitted the Ids. Shouldn't be long before they are migrated. For the future, there won't be a need to go thru this process. I don't know at what point the cutoff was, but it would appear yours were prior to the changeover.

@YutongTie-MSFT, you are correct. Any created going forward will be on the new ranker.

**Comment by stevkan** [comment]
@YutongTie-MSFT, the endpoints have been migrated. Can you have your customer retest and check the confidence scores he is now receiving?

**Comment by YutongTie-MSFT** [comment]
@stevkan Sure. @EdwinOtten Please tell us if you still have any challenge.

**Comment by EdwinOtten** [comment]
@stevkan Thanks for migrating the rankers! I have trained and published the KB (`c9127347-94a5-4614-92a3-af295b7d7130`) again and most of the results now match the documentation! 🎉Except for one, which is still quite far off..

I haven't changed the KB since last time, so it's content is still [the same.](https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/148#issuecomment-442100885)

Please check the results below:

Query | Typical Score | My score (ranker v0) | My score (updated ranker)
-- | -- | -- | --
My changes aren't updated in Knowledge base after publish | 90 - 100 | 43.09 | 54.27❗
I published my KB but it's not updated | 70+ | 49.34 | ✅ 74.83
Should I save my updates before I publish my KB? | 50 - 70 | ✅ 54.49 | ✅ 58.07
What does the save and train do? | 30 - 50 | None | ✅ 40.89
Where can I add synonyms to my KB | < 30 | ✅ 16.75 | ✅ 28.7
How much does the service cost | 0 | 8.57 | ✅ None

**Comment by stevkan** [comment]
Thanks, @EdwinOtten. I'll work with the QnA team to see what we can discover. I'm glad it's largely aligning, tho.

**Comment by stevkan** [comment]
Hi @YutongTie-MSFT, @EdwinOtten,

The remedy is to add 'KB' and 'knowledge base' as synonyms. Originally, this action was in the documentation but was removed in a previous iteration. It is going to be added back in. As an option, you can read more about score improvement guidelines (including adding synonyms) in [this doc](https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/concepts/best-practices#rankingscoring).

As this should address all your concerns I'm going to close the issue. If you continue to experience problems related to this, please feel free to reopen the ticket.

**Comment by EdwinOtten** [comment]
> The remedy is to add 'KB' and 'knowledge base' as synonyms.

The [documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/concepts/best-practices#use-synonyms) recommends to use ***word alterations*** for this, referring to the [V4 API reference](https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75fd). 

I cannot find the *word alterations* feature in the qnamaker.ai interface, are *word alterations* only accessible via API?

**Comment by robkostermans** [comment]
How can we check if the rankers are updated? Ik see the same kind of pattern; after export/import training/retraining the same question yields 80% in old database and 20% in new database.

(old kb: 98219dda-6ee5-4bcc-bf59-4b5b5f37723e)
(new kb: b15700ec-9c74-4359-b163-41834c68b346)
