### ISSUE TITLE
Manage KnowledgeBase

### ISSUE THREAD

**Issue by JulienM28** [Microsoft/BotBuilder-CognitiveServices#156]
I want to manage my KB from an external application.

The only way I found with the current api is to "download" the whole KB.

If I want to choose only Entries filtered on a word contained in questions and/or answers, I can't, and I must do the filter on the whole set after downloading the whole KB.

Is there something planned to have an API for that use ?

Thanks.

**Comment by Zerryth** [comment]
@JulienM28 What is it specifically that you are trying to achieve by identifying entries with certain words?

It's possible that the APIs do not have the implementation in the way that you are looking for, however clarification on what you'd like to do might illuminate otherwise...
___
Are you building a bot using the v4 Bot Builder SDK? And are you specifically interested in the `GenerateAnswer` endpoint? 

As of QnA Maker v3 (I believe--and most current is v4), they've introduced the concept of `strictFilters` and `metadataBoost`, and integration with the Bot Builder SDK came recently in the `4.2.0` update.

With this, you can build your QnA KB to include metadata, and then apply `strictFilters` options in your call to the QnA service from withing your bot with the use of `.getAnswers()` method

* [QnAMaker API - metadata](https://westus.dev.cognitive.microsoft.com/docs/services/597029932bcd590e74b648fb/operations/59703a928eb8131608e2f7a5)

* [User metadata and the GenerateAnswer API](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/metadata-generateanswer-usage)

* [BotBuilder-Samples](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples): go to either `csharp_dotnetcore` or `javascript_nodejs` and find Sample `11.qnamaker`
___
But then again, you may be looking to do something else with your KB and not query for answers that contain a certain word. Clarify, and I'd be happy to investigate further! :)

**Comment by JulienM28** [comment]
We're working on an application to manage our KBs like the Microsoft tool:
![image](https://user-images.githubusercontent.com/23618436/50584368-6fb80380-0e6f-11e9-86ca-5c934a629828.png)

I just want to be able to filter entries in the KB and not download the whole KB.

Thanks

**Comment by Zerryth** [comment]
I see. It seems as of now that the method you've described is the only way to go about what you're looking to do, however I have messaged the QnA team and will update you if they plan to expand to such a feature in the QnA API in the future.

**Comment by Zerryth** [comment]
@JulienM28 Sweet, the team got back to me pretty much immediately :)

They confirmed that currently there is not another method to do what you're looking for, and nor is it a part of their near-term plans. 

They are adding it to their product backlog and will prioritize on implementing based on requests and number of feature asks.

If they think of another method, they will update me sooner, they noted.

**Comment by JulienM28** [comment]
Thank you for your answer.
