### ISSUE TITLE
QnAMakerDialog line88 not Cortana friendly

### ISSUE THREAD

**Issue by Micro-Muncher** [microsoft/BotBuilder-CognitiveServices#161]
Cortana receives a message with empty text on invocation without intent, for example, "Open MySkill".

Because of this, around line 88, if the text is null, the turn exits with no reply. This manifests itself as a timeout on Cortana.

If the message text is null, typically a welcome message should be displayed.

**Comment by EricDahlvang** [comment]
I think this is something the consuming code is responsible for guarding against.  There are other scenarios where bots receive no text, such as when an Adaptive Card Submit button is clicked (the activity.Value property will contain json of values, and text will be empty).  Rather than change the underlying qnamaker dialog to send a welcome message on empty text, the consuming code can check the text property and not use qnamakerdialog if there is no text present.

**Comment by bw-kforce-ms** [comment]
It seems to me that single entry/single exit - the exit paths should be consistent.  If the input is valid, we return something.  If it is invalid, we do nothing (not even log). Most of our examples are shims that shunt the activity/message to someone that processes the message. If we intend to fail open, we should at least log that we've done so.  I've had 5 incidents supporting partners for this specific case.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
