### ISSUE TITLE
[QnA Maker] Issue with recognizing emojis / emoticons

### ISSUE THREAD

**Issue by Stardox** [Microsoft/BotBuilder-CognitiveServices#169]
### Problem description:
I would like to train my [QnA Maker](https://www.qnamaker.ai/) model, so that it correctly recognizes emojis (or group of emojis) and returns the relevant key which I will then handle further in my code. As a simple example I added following inputs and associated them with the QnA answer `smalltalk.emoji.grin`:
`😀`, `:D` and `grinning face`

This is how it looked like after I finished the training (notice that I can search the knowledge base using unicode emoji):
![01](https://user-images.githubusercontent.com/4964894/56207781-e90ae900-604f-11e9-9de0-10649d2ef6b1.PNG)

However when I tried to test the knowledge base, QnA did not recognize the `😀` and neither the `:D`:
![02](https://user-images.githubusercontent.com/4964894/56208014-6b93a880-6050-11e9-91c5-43fc43985437.PNG)

I also tried to call the QnA Maker's Generate Answer API directly by passing the both raw and UTF encoded emoji, but that did not work neither:
```
{
  "question": "😀",
  "top": 3,
  "userId": "Default",
  "isTest": true
}
```
```
{
  "question": "\ud83d\ude00",
  "top": 3,
  "userId": "Default",
  "isTest": true
}
```
Response for both of the above scenarios:
```
{
  "answers": [
    {
      "questions": [],
      "answer": "No good match found in KB.",
      "score": 0.0,
      "id": -1,
      "metadata": []
    }
  ]
}
```
### Question
How do I correctly train my QnA model so that it can correctly handle the emojis (both unicode and textual) or any other _complex_ unicode characters? This seems to be supported by [LUIS](https://www.luis.ai/) as it correctly categorizes the intent in case that I input emoji into it.

**Comment by stevkan** [comment]
As you've discovered, QnAMaker doesn't know how to handle emojis coming in an activity from the bot. Therefore, you need to build in the functionality. This example demonstrates setting up via Node, however the implementation would essentially be the same for C#. There are nuget packages that can be installed, like [Unicode.net](https://www.nuget.org/packages/Unicode.net). (I've purposely kept this demonstration simple. Alter as needed.)

For Node, you can download and install the NPM package [node-emoji](https://www.npmjs.com/package/node-emoji) which has a number of nicely packaged methods. Once installed, add the following into your onTurn handler along with the necessary QnA bits. You can also setup to allow user's the send literal emoji's which QnA Maker can also match on (see pic below).

See inline comments for further explanation.

```js
async onTurn(turnContext) {
    if (turnContext.activity.type === ActivityTypes.Message) {
        await turnContext.sendActivity(`Try sending ':heart:' or ':pizza:'`);

        // Strips out ":" from the user text to get the raw input
        let userText = turnContext.activity.text.replace(/:/gi, '');

        // Adds ":" to the new variable to compare if the original text input is an emoji
        if (':' + userText + ':' === turnContext.activity.text) {
            let emojiMsg = emoji.emojify(turnContext.activity.text);
            await turnContext.sendActivity(`Looks like I have that emoji! ${ emojiMsg }`);
            await turnContext.sendActivity(`Checking QnAMaker for a response to the image.`);

            // Perform a call to the QnA Maker service to retrieve matching Question and Answer pairs.
            const qnaResults = await this.qnaMaker.generateAnswer(emojiMsg);

            // If an answer was received from QnA Maker, send the answer back to the user.
            if (qnaResults[0]) {
                console.log('QNA Results: ', qnaResults[0].answer);

                // Assigns the emoji response and sends as an activity message to the user
                let emojiResponse = emoji.emojify(qnaResults[0].answer);
                await turnContext.sendActivity(emojiResponse);

            // If no answers were returned from QnA Maker, reply with help.
            } else {
                await turnContext.sendActivity('No QnA Maker answers were found. This example uses a QnA Maker Knowledge Base that focuses on smart light bulbs. To see QnA Maker in action, ask the bot questions like "Why won\'t it turn on?" or "I need help."');
            }
        } else {
            await turnContext.sendActivity(`You said: ${ turnContext.activity.text }`);
        }

    // Sends a quick greeting message to the user.
    // :heart: exists as an emoji but isn't in QnAMaker, so it responds "No answer".
    // :pizza: exists as an emoji and has a matching QnA pair and returns the :grinning: emoji (😀)
    // Because the user text in parsed and matched, simply typing "pizza" returns "No answer"
    } else if (turnContext.activity.type === ActivityTypes.ConversationUpdate &&
                turnContext.activity.recipient.id !== turnContext.activity.membersAdded[0].id) {
        await turnContext.sendActivity(`Try sending ':heart:' or ':pizza:'`);
}
```

![image](https://user-images.githubusercontent.com/18403946/56253633-0f418080-6072-11e9-9cdf-309e02314ea3.png)

I convert both `:pizza:` and "🍕" to "🍕" and always return "😀" . Because I parse the user text, if I simply type "pizza", nothing is returned. Without the parsing, "pizza" would match on `:pizza:` and return the second response.

![image](https://user-images.githubusercontent.com/18403946/56253240-5f1f4800-6070-11e9-8f56-96c32c1ba441.png)

The flow is far from perfect, but then that wasn't the point. Hope of help!
