### ISSUE TITLE
QnaMaker return results with questions that do not exist in the knowledge base

### ISSUE THREAD

**Issue by samsaavel** [microsoft/BotBuilder-CognitiveServices#179]
In the knowledge base (where there are some questions with their respective answer), I am getting in QnA Maker a 95% matching score even with some wrong answers, actually, I set the score to 94%, assuming that by setting a higher score, it could give more precise answers. Below is an example:
Base Knowledge:
ID-- Question-- Answer
1-- 01 Warehouse Structure.wmv-- link to multimedia file
2-- 01 Warehouse Structure-- link to pdf file
3-- Center Structure - Zones Tpe Final R2R 1.2-- link to excel
file

- Case 1: Ask "Warehouse structure" 
the answers for ID 1, 2 and 3 with scores of 95, 95, 94 respectively.

- Case 2: ask "Cost structure"
the answers for ID 1 and 2 with scores of 95, 95 respectively
 
- Case 3: ask "structure"
the answers for ID 1, 2 and 3 with scores of 95, 95, 95 respectively

In Case 2 the question asked is not in the knowledge base, yet it is assigning it a score of 95. So,
my question is, why I am getting answers to non-existent questions if I have a high score set, how can I fix it?

**Comment by Zerryth** [comment]
@samsaavel, I think there's a misconception here about how QnA Maker functions. It is not a tool that simply matches questions that are **exactly** matching the string in a knowledge base--there's not much 'cognitive' functionality, if that's how the service functioned.

Underlyingly, it appears that "Cost structure" is detected as question that matches answers in your KB that should be answers to your "Warehouse structure" question, because both questions contain the word "structure"--so it just appears that the algorithm figured, ok, "Cost structure" doesn't match 100% (i.e. with 1.0 confidence) as any question that's currently in the KB, but I will match it to the answers for "Warehouse structure" because that question shares keyword "structure".
___

### How to Have QnA Maker Properly Detect Answers to Questions as Intended

The short summary to your problem is you simply need to train your QnA KB to have it detect the questions properly. There are many articles that go over how to do this available in the QnA docs. A few techniques include:

_[Best Practices of a QnA Maker knowledge base](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/best-practices#creating-good-questions-and-answers)_
* Adding relevant alternative questions
* At the bot level, using metadata tags

_[Test your knowledge base interactively in QnA Maker](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/test-knowledge-base)_
* Inspect the answers given in the QnA Test Panel, and correct the top scoring answer

Be sure to Save and Train to keep any updates you make to your KB.
___
Closing the issue here, as the Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](https://stackoverflow.com/search?q=%23botframework). 

The official Bot Framework GitHub repos are the preferred platforms for submitting **bug fixes** and **feature requests**.
