### ISSUE TITLE
how qnamakers' multi-turn feature and context work with generateAnswer api?

### ISSUE THREAD

**Issue by shikelong** [microsoft/BotBuilder-CognitiveServices#180]
Hi, I am using qnamaker's multi turn conversation support. But When I call generateAnswer api. I can't get the answer I expected. Seem context params in generateAnswer api not work.

Note: *I just using QnaMarker's portal and console. Not in my Application or Azure bot Services.*

### This is test data in my Knowledge base:
![2019-07-24_115710](https://user-images.githubusercontent.com/4499997/61762197-27acfe00-ae0c-11e9-8bf8-3cf5b652aaf2.png)

![2019-07-24_115843](https://user-images.githubusercontent.com/4499997/61762295-85d9e100-ae0c-11e9-89cd-27118c18072f.png)

### When I type test query, "OpenSource" cannot get match item from Knowledgebase:

![2019-07-24_115634](https://user-images.githubusercontent.com/4499997/61762227-3b586480-ae0c-11e9-9038-4487be29b238.png)

### There are screenshot of dev tools:

![2019-07-24_115748](https://user-images.githubusercontent.com/4499997/61762314-8ecab280-ae0c-11e9-9be5-bdf6320f27f2.png)
![2019-07-24_115758](https://user-images.githubusercontent.com/4499997/61762316-90947600-ae0c-11e9-9db6-bdbc8dbba036.png)

Both in test or prod env I can't get the  "openSource" option's answer.
 I can't understand this . **Is anywhere exist a option like "enable multi turn conversation" need me to turn on?**

Thank you.

**Comment by shikelong** [comment]
I use a display text that different from the fellow-up prompt's question.
I guess this is the reason I got a not match response.

But I thank different and flexible display text is a important feature in the real world.

**Comment by Zerryth** [comment]
@shikelong, you're correct in that you're getting "No good match found in KB." because the question in your follow-up prompt is different from the choice that you selected when the KB first responds with "I'm good. Thank you." The choice you selected, "OpenSource" is used as the next "question" value. And from just the small snippet that you've shown us of your KB in your screen shot, it looks like you don't have anything in the "Question" column with "OpenSource" as a value, hence the lack of matching to a Q&A pair

____

Working Multi-Turn Example

First question is "milk" with 2 follow-up prompts ("milking techniques", "milk nutrition facts")

![image](https://user-images.githubusercontent.com/35248895/61816102-83718a00-ae00-11e9-9492-cab87ed1cfe9.png)

I select "milking techniques" choice, which queries the KB for question with "milking techniques" and resolves properly to the answer I set to "milking techniques" ("this is the technique: blahblahblah")
![image](https://user-images.githubusercontent.com/35248895/61816126-8e2c1f00-ae00-11e9-84f1-0398ceb90dce.png)

___

> I use a display text that different from the fellow-up prompt's question.
> I guess this is the reason I got a not match response.
> 
> But I thank different and flexible display text is a important feature in the real world.

If you want information that you don't necessarily want displayed to the user, but still want data attached to the Q&A pair, you can take advantage of [adding metadata](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/metadata-generateanswer-usage).
___

If you have any further How-To questions, please post your question on Stack Overflow, as GitHub is the preferred area for posting issues regarding bugs in the SDKs/Cognitive Services.

**Comment by shikelong** [comment]
I got it. Thank you.
